created hook useFetch
AntonKulagin/MFD pull request #2
Opened 2023-03-10 16:24 UTC by AntonKulagin

2023-03-11 11:17 UTC, taraswww777 commented on react-course/src/App.jsx
> +import './App.css';
начиная с React 18 можно файлы называть просто `*.js|ts`

2023-03-11 11:23 UTC, taraswww777 commented on react-course/src/hooks/useFetch.js
> +    if (params) return `?_limit=${params._limit}`;
Если в объекте params будет много значений, то лучше обойти весь объект при помощи `Object.keys()` или как в этой спеке https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

2023-03-11 11:31 UTC, taraswww777 commented on react-course/src/hooks/useFetch.js
> +  const getFetchLimit = (params) => {
название функции вводит в заблуждение, оно вводит в заблуждение. 
Она скорее готовит url params.

2023-03-11 11:35 UTC, taraswww777 commented on react-course/src/hooks/useFetch.js
> +  const getFetchLimit = (params) => {
ф-ю getFetchLimit можно вынести и  описать перед useFetch

2023-03-11 11:36 UTC, taraswww777 requested changes
Нужны правки в соответствии с комментариями

2023-03-11 12:35 UTC, AntonKulagin commented on react-course/src/hooks/useFetch.js
> +    if (params) return `?_limit=${params._limit}`;
Применил `Object.keys()`

2023-03-11 12:36 UTC, AntonKulagin commented on react-course/src/hooks/useFetch.js
> +  const getFetchLimit = (params) => {
Вынес функцию наружу. Переименовал на `getFetchEndpoint`

2023-03-11 12:57 UTC, AntonKulagin commented on react-course/src/hooks/useFetch.js
> +    if (params) return `?_limit=${params._limit}`;
Применил `Object.keys(params).map(item => {})`. Если будут много значений, полагаю, что можно будет применить reduce. Главное понять, какие запросы потребуются.

2023-03-11 18:58 UTC, taraswww777 commented on react-course/src/hooks/useFetch.js
> +  const getFetchLimit = (params) => {
уже лучше

2023-03-11 18:59 UTC, taraswww777 approved these changes

2023-03-11 18:59 UTC, taraswww777 commented on react-course/src/App.jsx
> +import './App.css';
ок

2023-03-12 10:34 UTC, taraswww777 requested changes
Есть замечания

2023-03-12 10:34 UTC, taraswww777 commented on react-course/src/hooks/useFetch.js
> +      if (item === '_limit') {
И какой смысл? Другие параметры не применятся.
Например параметры `{_limit: 3, sortBy: 'name', sortDirection:'desc'}` должны превратиться в строку `?_limit=3&sortBy=title&sortDirection=desc`
Метод массива join может помочь

2023-03-19 07:44 UTC, taraswww777 approved these changes

2023-03-19 07:44 UTC, taraswww777 commented on react-course/src/hooks/useFetch.js
> +        ...params,
Конкретно тут деструктуризация избыточна

2023-03-26 08:51 UTC, closed without merging